<?php

namespace App\Models\Api;


use App\Models\Core\User;
use Illuminate\Http\JsonResponse;

class Response extends JsonResponse
{

    public function __construct($data = null, $status = 200, $headers = [], $options = 0)
    {
        $headers['Access-Control-Allow-Origin'] = '*';
        $headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE, OPTIONS';
        parent::__construct($data, $status, $headers, $options);
    }

    /**
     * @param array $data
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     */
    public function setData($data = [])
    {
        $route = request()->route();
        $token = null;

        if ($route) {
            $token = $route->getParameter('token');
        }

        if(!$token instanceof Token) {
            if($token != null) {
                $token = Token::findByToken($token);
            } else {
                $token = new Token();
            }
        }
        
        $resp = [
            'status' => $this->getStatusCode() == 200 ? 'success' : 'error',
            'statusCode' => $this->getStatusCode(),
            'accessLevel' => User::getType($token),
            'response' => $data,
        ];
        return parent::setData($resp); // TODO: Change the autogenerated stub
    }
}
